# Generated by Django 2.0.4 on 2018-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
